Add v0.17.0.0-rc4 for dustinface
dashpay/gitian.sigs pull request #117
Opened 2021-04-12 12:04 UTC by xdustinface

2021-04-12 23:18 UTC, UdjinM6 requested changes
Hashes and sigs looks good but there should be no `v` in folder names

2021-04-13 06:17 UTC, xdustinface commented
Ops, seems like this happens if you build with `-c ... <tag>`. Looks better without `-c` and only the version without the `v` prefix :see_no_evil:

2021-04-13 12:37 UTC, UdjinM6 approved these changes
ACK

2021-04-14 20:05 UTC, PastaPastaPasta approved these changes

2021-04-14 20:05 UTC, merged